### ISSUE TITLE
No command echo received and Unexpected exception: Failed to retrieve projector model on BenQ X3000i

### ISSUE THREAD

**Issue by c1em3ntchua** [rrooggiieerr/homeassistant-benqprojector#1]
Hi rrooggiieerr, first of all I would like to say a big thank you for writing this integration for Home Assistant. I've been trying to write one myself but I haven't really figured out Python yet.

I am getting the above two errors when trying to add the integration to my HA. The log details are below:

--- No command echo received ---
Logger: benqprojector.benqprojector
Source: custom_components/benqprojector/config_flow.py:114
Integration: benqprojector
First occurred: 10:00:20 PM (6 occurrences)
Last logged: 10:10:30 PM

No command echo received
Response: *modelname=x3000i#
Unexpected response: []

--- Unexpected exception: Failed to retrieve projector model ---
Logger: custom_components.benqprojector.config_flow
Source: custom_components/benqprojector/config_flow.py:114
Integration: benqprojector
First occurred: 10:00:20 PM (2 occurrences)
Last logged: 10:10:30 PM

Unexpected exception: Failed to retrieve projector model
Traceback (most recent call last):
  File "/config/custom_components/benqprojector/config_flow.py", line 65, in async_step_setup_serial
    info = await self.validate_input_setup_serial(user_input, errors)
  File "/config/custom_components/benqprojector/config_flow.py", line 114, in validate_input_setup_serial
    projector.connect()
  File "/usr/local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 133, in connect
    assert model is not None, "Failed to retrieve projector model"
AssertionError: Failed to retrieve projector model

--- End ---

I note that the projector does reply correctly, but somehow an unexpected response was detected, preventing the script from going further. Please let me know what I can do to help troubleshoot the issue.

**Comment by rrooggiieerr** [comment]
Hi @c1em3ntchua, great to see someone is already trying out my BenQ integration, especially since it's only 5 day's on Github. The current version on Github is actually not very stable, but a new version is coming very soon which wil probably be workable and has many more features. I'll get back to you when that's the case

**Comment by c1em3ntchua** [comment]
Thanks a lot [rrooggiieerr](https://github.com/rrooggiieerr), appreciate the reply. Looking forward to the update :)

Off topic, but would appreciate if you could add a `smartsystem` into the `sources` list.

**Comment by rrooggiieerr** [comment]
@c1em3ntchua, I'm not sure what you mean by a smartsystem, but the library I use (and also wrote) in this integration, uses a per projector model configuration for supported commands and modes.

https://github.com/rrooggiieerr/benqprojector.py

Currently only my own model W1110 is in there, but if you send me a list of supported modes I can add a configuration for your projector.

Actually the BenQ Projecotr library has an undocumented detection mode which detects what is supported by your model

**Comment by c1em3ntchua** [comment]
@rrooggiieerr the X3000i manual is available [here](https://esupportdownload.benq.com/esupport/PROJECTOR/UserManual/X3000i/X3000i_UM_EN_220121234753.pdf).

smartsystem seems to be the name BenQ assigns to the 3rd HDMI for an internal Android TV stick.

I did notice the detection mode in the code. Pretty cool feature!

**Comment by rrooggiieerr** [comment]
@c1em3ntchua , new release of the BenQ Projector library and HA integration should solve your initial issue.

**Comment by c1em3ntchua** [comment]
Hey @rrooggiieerr, the new library does solve the initial issue, but other issues pop up afterwards. I believe it's library related.
