### ISSUE TITLE
Can the Mini USB slot be used to control BenQ W2700?

### ISSUE THREAD

**Issue by bannert1337** [rrooggiieerr/homeassistant-benqprojector#13]
I have a BenQ W2700 and saw that it has a mini USB slot on the back. I wondered if it could be used as an alternative to using the serial com slot. Anyone tried this yet?

**Comment by rrooggiieerr** [comment]
The USB Mini-B port is there for firmware upgrades

**Comment by rrooggiieerr** [comment]
I hope this answered your question, so I'm closing the issue
