### ISSUE TITLE
Option to use Network Serial (iTach Flex)?

### ISSUE THREAD

**Issue by frozendevl** [rrooggiieerr/homeassistant-benqprojector#16]
Hello, first of all, thanks for creating this, awesome idea. Is it possible to use a network RS232 device with this? I tried both the network and serial option, but neither worked for this use case and it seems if I could enter an IP address with the "serial" option, it would do what I need it to then. Is this something that is possible and if so, something you can consider adding? For context, I have the X3000i.

**Comment by rrooggiieerr** [comment]
I'm not familiar with the iTach Flex, but if it accepts telnet connections to send commands to the serial port this should just work.

If the network option does not work, does a manual telnet connect and accept commands like described in the readme?

**Comment by frozendevl** [comment]
Appreciate your help, can close this for now. I've tried the iTach and a cable connection and not going through directly with either Telnet or Serial. So I have a bigger issue at hand I'll need to troubleshoot further.
