### ISSUE TITLE
BenQ TK810 Turns on and then changes to unavailable

### ISSUE THREAD

**Issue by davemenkehorst** [rrooggiieerr/homeassistant-benqprojector#18]
[So](url) i bought a USB to Serial convertor and did a pass trough from proxmox. 
The integration loads an i can turn on my projector! 
After 10 seconds, the integration crashed. After multiple attempts, i can re-add the integration(after a lot of failures) and can successfully turn it on.

> Deze fout is ontstaan door een aangepaste integratie.
> 
> Logger: benqprojector.benqprojector
> Bron: custom_components/benqprojector/config_flow.py:156
> integratie: BenQ Projector (documentatie, problemen)
> Eerst voorgekomen: 17:29:43 (6 gebeurtenissen)
> Laatst gelogd: 17:31:33
> 
> Failed to get projector command prompt, is your projector properly connected?
> Unexpected response: b'S'
> Unexpected response: b'\x93'
> 

Then if i successfully add the projector:

> Logger: benqprojector.benqprojector
> Bron: runner.py:189
> Eerst voorgekomen: 17:33:18 (16 gebeurtenissen)
> Laatst gelogd: 17:33:55
> 
> Command *pp=?# illegal format
> Command *ltim2=?# illegal format
> 

and

> Deze fout is ontstaan door een aangepaste integratie.
> 
> Logger: benqprojector.benqprojector
> Bron: custom_components/benqprojector/__init__.py:235
> integratie: BenQ Projector (documentatie, problemen)
> Eerst voorgekomen: 17:33:18 (1 gebeurtenissen)
> Laatst gelogd: 17:33:18
> 
> Command *macaddr=?# illegal format

Is the integration failing because of the unsupported commands? (like Read Mac Address <CR>*macaddr=?#<CR>)

I'm using the TK810. So i'm refering to this PDF 

https://esupportdownload.benq.com/esupport/PROJECTOR/Control%20Protocols/TK810/TK810_RS232%20Control%20Guide_0_Windows10_Windows7_Windows8.pdf

Log 1:
[home-assistant_benqprojector_2024-09-21T15-41-21.394Z.log](https://github.com/user-attachments/files/17084680/home-assistant_benqprojector_2024-09-21T15-41-21.394Z.log)

Log 2:
[home-assistant_benqprojector_2024-09-21T15-46-40.210Z.log](https://github.com/user-attachments/files/17084685/home-assistant_benqprojector_2024-09-21T15-46-40.210Z.log)

Log 3:
[Uploading home-assistant_benqprojector_2024-09-21T15-58-21.211Z.log…]()

And after a period of time i get this in CLI
<img width="403" alt="Scherm­afbeelding 2024-09-21 om 18 29 52" src="https://github.com/user-attachments/assets/ca1532a2-b7c4-4c39-bff7-49394ccc2778">

**Comment by rrooggiieerr** [comment]
Hi @davemenkehorst, the integration is not failing due to failing commands. My suspicion is that the speed of the serial connection is to high. You can change the speed in the menu of your projector and then select the same speed when installing the integration

**Comment by davemenkehorst** [comment]
> Hi @davemenkehorst, the integration is not failing due to failing commands. My suspicion is that the speed of the serial connection is to high. You can change the speed in the menu of your projector and then select the same speed when installing the integration

I’m running at 9600 (from the tk810 manual). Which speed do you recommend?

**Comment by rrooggiieerr** [comment]
9600 is actually quite slow. But if it can't be changed than there's nothing we can do there. I don't use virtualisation myself, so you're on your own regarding pass trough etc.

Maybe you can try the latest code from GitHub, there are some changes which have not yet been released in a version.

in _Developer tools_ > _Actions_ do the following:
```
action: update.install
target:
  entity_id: update.benq_projector_update
data:
  version: master
```

**Comment by davemenkehorst** [comment]
> 9600 is actually quite slow. But if it can't be changed than there's nothing we can do there. I don't use virtualisation myself, so you're on your own regarding pass trough etc.
> 
> Maybe you can try the latest code from GitHub, there are some changes which have not yet been released in a version.
> 
> in _Developer tools_ > _Actions_ do the following:
> 
> ```
> action: update.install
> target:
>   entity_id: update.benq_projector_update
> data:
>   version: master
> ```

The update didn't work, unfortunately. 
Trying to find information about the Wifi to rs232 bridge but information is old and can't find any useful tutorial. Is a generic guide like [this](https://diyables.io/products/rs232-to-ttl-converter-module) compatible with this integration? Or any more info about your example esp32 on the github page?

**Comment by davemenkehorst** [comment]
I made a test with a band new raspberry pi and the USB to RS232 cable. Home assistant bare metal. Exactly the same problem. 
It turns on and thats it

_I bought you a coffee btw_

**Comment by rrooggiieerr** [comment]
Thanks for the coffee.

For the RS232 WiFi bridge you can have a look at [ESP-link](https://github.com/jeelabs/esp-link)

You could try to enable debug logging and post the results.

You can also try to run the [benqprojector CLI](https://github.com/rrooggiieerr/benqprojector.py) in debug mode and post the results.

_I'm traveling for the next two weeks so am replying to you from my hotel room while I'm having a vacation btw_

**Comment by rrooggiieerr** [comment]
@davemenkehorst, did my recommendations have any results?

**Comment by davemenkehorst** [comment]
unfortunately the projector does not work via a local serial port either. it turns on and then there is no contact with it anymoreOp 7 okt 2024 om 13:10 heeft rrooggiieerr ***@***.***> het volgende geschreven:﻿
@davemenkehorst, did my recommendations have any results?

**Comment by davemenkehorst** [comment]
> If it turns on using the BenQ Projector integration than there should be at least some contact. The log file should give some details, especially when debugging enabled.
> 
> If the serial port really doesn't work than that's a hardware problem and I can't be of any help

If i use my projector directly to a windows PC, it turns on(same as your intergration), after that the projector doesn't respond anymore. So i think that has to work first

**Comment by rrooggiieerr** [comment]
> If i use my projector directly to a windows PC, it turns on

Is that turning on using a command over the serial cable, or does it turn on due to a HDMI CEC command?
