### ISSUE TITLE
Network Support W5700

### ISSUE THREAD

**Issue by coehne** [rrooggiieerr/homeassistant-benqprojector#3]
Hi!
I have a W5700 with LAN support.
Want to figure out how to make it run? :)
Unfortunately the Web UI of the projector is done with adobe flash...

Do you have any idea how to send the commands to the projector over LAN?

**Comment by coehne** [comment]
Using the pjlink cli (https://github.com/macoss/pjlink-cli) I was able to send "POWR 0" to turn the projector off and "POWR 1" to turn it back on. "LAMPE" also worked for me to get the lamp hours. Other commands from the benQ manual don't seen to work. And had to google for others who tried POWR 0 insted of POWER OFF like stated in the manual

Sources: The BenQ Networking Manual (https://esupportdownload.benq.com/esupport/PROJECTOR/UserManual/MH733/NG_EN_210428143533.pdf)

**Comment by coehne** [comment]
yeah, so I figured, the basic functions of the projector work fine with the already integrated PJLink integration :)
https://www.home-assistant.io/integrations/pjlink/

So nevermind I guess?

**Comment by rrooggiieerr** [comment]
Hi @coehne , good to hear you've already got your projector working using PJLink. I wasn't aware the (some?)  BenQ network connected projectors support PJLink, I will actually add this to the readme so future users can easily find this info.

The BenQ Networking Manual you link to is for the model MH733 projector which might explain why the commands differ from your model W5700 projector. To my understanding there are different command protocols for different series of BenQ projectors, and I can tell you first hand that even if you have the command set that officially applies to your particular model even then there are errors and deviations to what is documented.

If it's ok with you I close this issue.

**Comment by coehne** [comment]
Hi @rrooggiieerr,
Yes, in the manual for my projector there is just a non working reference link to the "BenQ Network Projector Operation Guide" which is a generic one like the one I posted previously. So I guess there is no good documentation :/

However, I figured that the PJlink integration only allows to add the projector as media player which makes it integrate badly into automations. If I use your integration using the serial port, will the projector then be added as a device? Sorry, I am also very new to HA...

**Comment by rrooggiieerr** [comment]
Yes and no. When you use the serial port **and** your projector uses the same communication protocol as my integration implements then you will get an extra media player device which you can use to control on/off, input source and volume. On top of that you will get a dozen entities for color temperature, brightness, contrast.

<img width="343" alt="Screenshot 2022-12-07 at 19 47 48" src="https://user-images.githubusercontent.com/18603534/209695873-77d1e28b-3020-4836-a39f-039cc27bb814.png">

<img width="559" alt="Screenshot 2022-12-07 at 19 48 05" src="https://user-images.githubusercontent.com/18603534/209695874-88d0c25e-e1e6-4c1c-8b5a-66693dd07d98.png">

<img width="287" alt="Screenshot 2022-12-07 at 14 03 32" src="https://user-images.githubusercontent.com/18603534/209695866-7cb0c4ef-55b5-43d1-9b62-cb7d30f96500.png">

![Screenshot 2022-12-07 at 19 46 44](https://user-images.githubusercontent.com/18603534/209695872-e1ec3d15-a6a4-4db1-a869-dac4cf95b1a9.png)

**Comment by rrooggiieerr** [comment]
@coehne can you connect to port 8000 as described in this document?

https://esupportdownload.benq.com/esupport/Projector/Control%20Protocols/PU9530/RS232%20Control%20Guide_0_Windows7_Windows8_WinXP.pdf

**Comment by coehne** [comment]
Ah nice. Didn't see that before. I'm on the road now but will give it a try and come back to you.

**Comment by coehne** [comment]
@rrooggiieerr unfortunately, nothing happens, when I connect to port 8000 like in the manual. I only get a black screen when using the tera term program from the manual. Didn't figure out how to send the control commands with tera term.
I guess I will first try to control the projector via the PJlink integration and hope that will work :) If not, I'll try IR or buy a RS232 to USB cable, but that would feel like giving up on the LAN integration 😞

**Comment by rrooggiieerr** [comment]
So it does connect? At least that's something. I think if you hit enter you will get a command prompt `>` and then you could type `*pow=?#` to get the projector power state

**Comment by coehne** [comment]
Yes, I only get a black terminal without any prompt or any reaction at all to any key presses.

**Comment by rrooggiieerr** [comment]
Do you use the telnet protocol?

**Comment by coehne** [comment]
I selected "other" like it was on the screenshot. Is it working via telnet?

**Comment by rrooggiieerr** [comment]
I have no idea, my projector doesn't have a network connection. But I'm guessing it's not encrypted like SSH but just plain text and then telnet should generally work

**Comment by coehne** [comment]
Nope, doesn't work when I select telnet, it just changes the port to 23. Same result sadly.

And you are not planning on adding PJlink support for your integration I guess 😃 ?

**Comment by rrooggiieerr** [comment]
Too bad! No, I'm not going to support PJLink, my projector doesn't support it. But feel free to use my integration as a blueprint to develop your own integration, or improve the existing PJLink integration. Good luck ;-)

**Comment by rrooggiieerr** [comment]
Hi @coehne, some time has passed, but the BenQ projector integration now also supports projectors with integrated network connections. I'm curious to know if your projector now also works. Would you be willing to give the integration a try again?

**Comment by coehne** [comment]
Hi @rrooggiieerr, sure thing, I solved it using the universal remote but I can give it a try again to test it.
