### ISSUE TITLE
Network connection

### ISSUE THREAD

**Issue by Duff-Box1** [rrooggiieerr/homeassistant-benqprojector#7]
Hi I have a BenQ TK850i which looks like it might work with this nice integration. I was going to use an rs232 to network adapter would this integration be able to connect to the projector with HA running on a pi? I don't have local access to the rs232 as my pi is a long distance apart. Many thanks.

**Comment by rrooggiieerr** [comment]
The integration currently does not support network connections, however I have the parts to built a serial to network adapter using [ESPlink-Firmware](https://github.com/jeelabs/esp-link) and have plans to implement that in the future.

What serial to network adapter are you using?

**Comment by tiduspup** [comment]
Hello Guys, 

serial over ip would be fantastic. Your integration looks really good. I was investigating Esp-Link with esp8266 wemos d1.

I tested esphome but you dont get as many infos / updated infos without a custom script

**Comment by Salamandar** [comment]
I currently have a W2000+ that doesn't have a LAN connection but a RS-232 port, and with a ESP8266 and ESPHome, I can configure my videoprojector over the network via a Home assistant service :
![image](https://github.com/rrooggiieerr/homeassistant-benqprojector/assets/6552989/068ac7e3-e70c-4809-aca7-4799370abaab)

Do you think this would be easy to adapt the current project to use a service instead of a serial connection ?

**Comment by Jinsin456** [comment]
> I currently have a W2000+ that doesn't have a LAN connection but a RS-232 port, and with a ESP8266 and ESPHome, I can configure my videoprojector over the network via a Home assistant service : ![image](https://user-images.githubusercontent.com/6552989/261546654-068ac7e3-e70c-4809-aca7-4799370abaab.png)
> 
> Do you think this would be easy to adapt the current project to use a service instead of a serial connection ?

Could you maybe go into a bit of detail regarding your setup please?

I'm very interested in bringing my TK700Sti into HA. I would only really need Power On / Off commands as it will be tied in with other things and I don't really care about the other settings but if I could get Power status that would be amazing!

**Comment by rrooggiieerr** [comment]
I just released a major update to the integration: network support. Still very much in beta since I don't own a networked projector. Let me know if it works for you.

**Comment by rrooggiieerr** [comment]
Hi! Since I didn't hear anything back on this issue I'm closing the issue
